const mongoose = require("mongoose");

const characterSchema = new mongoose.Schema({
    id: String,
    dateCreated: Date,
    npc: Boolean,
    name: String,
    race: String,
    class: String,
    subClass: String,
    level: Number,
    experiencePoints: Number,
    alignment: String,
    playerName: String,
    abilities: Object,
    proficiencyBonus: Number,
    savingThrows: Array,
    skills: Array,
    armorClass: Number,
    Initiative: Number,
    Speed: Number,
    maxHitPoints: Number,
    hitDice: String,
    passivePerception: Number,
    spellcastAbility: String,
    spellSaveDc: Number,
    spellAttackBonus: Number,
    spells: Array,
    featsTraits: Array,
    proficiencies: Array,
    languages: Array,
    inventory: Array,
    copperCount: Number,
    silverCount: Number,
    goldCount: Number,
    platinumCount: Number,
    personalityTraits: Array,
    ideals: Array,
    bonds: Array,
    flaws: Array,
    backstory: String,
});

const Character = mongoose.Model('Character', characterSchema);